✨ Feature: 로그인 기능 구현
M0IM/BE pull request #20
Opened 2024-07-04 14:05 UTC by yewonahn

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [x] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #14 

## 📌 개요
- 

## 🔁 변경 사항
✔ b976c56601664cc2c4c9355d583a150b3a50c9d0 : 로그인 구현

✔ f8764b40dd453b13c6c1346ad9021a03607f5230 : jwt 인증, 인가 로직 구현

✔ dd78b50d9904c78bc6bac283d3877fe053c8fd29 : jwt 인증, 인가 로직 구현

✔ 0739ade67ab102d5f1fb79f1e0942d2c06c10c6c : 순환 참조 에러 해결

**- 순환 참조 에러 해결**
refreshToken을 저장하는 로직을 구현하던 중, JwtFilter, JwtUtil, RefreshTokenService에 대해 순환 참조 에러가 발생했습니다. 개발 과정에서 불필요한 생성자 주입으로 인한 문제였고 코드 수정으로 해결했습니다.

**- JwtProvider -> JwtUtil 네이밍 변경**

**- ExtractTokenArgumentResolver가 @ExtractToken에 대해서만 작동하도록 설정**
 토큰 재발급 요청 시, @ExtractToken 커스텀 어노테이션을 사용해서 요청의 헤더에서 jwt 토큰을 추출하고 해당 토큰의 유효성 검증 후, 메서드 인자로 주입하도록 구현하였습니다. 메서드 인자에 @ExtractToken 어노테이션이 붙어 있는지 확인하도록 코드를 수정했고 "Bearer "로 시작하지 않는 경우, AuthException을 발생시키도록 수정했습니다.

**- 커스텀 어노테이션 @ExtractToken ArgumentResolvers에 추가**

**- 토큰 재발급 관련 로직 리팩토링**
기존엔 토큰 재발급 관련 로직인 reissueToken을 RefreshTokenService에 구현했었습니다. AuthService의 reissueToken에서 RefreshTokenService의 reissueToken를 한번 더 호출하는 로직이였습니다. 중복 호출을 발생시키고 단일 책임 원칙이 지켜지지 않는다고 판단됐고 재발급 로직 관련 reissueToken을 RefreshTokenService에서 제거하고 AuthService에서 실행되도록 수정했습니다.

✔ e727d40fad7ae6f56665d84f9697b36d9cd74cdb : RefreshToken 저장소 redis로 변경

**- RefreshToken 저장소 redis로 변경**

**- RefreshToken 관련 로직 따로 분리하여 RefreshTokenService에 구현**
Jwt 토큰의 생성 및 검증과 관련된 로직들은 JwtUtil에 구현되어 있습니다. RefreshToken의 경우 refreshToken의 저장, 삭제, 검증의 비즈니스 로직이 있는데 관심사 분리를 위해 RefreshTokenService를 따로 두었습니다.

**- ReissueTokenResponse 제거**
최초 토큰 생성인 로그인에서의 토큰 응답인 TokenResponse에서 accessToken과 refreshToken을 주는 것과 동일하게, accessToken 유효 시간 만료로 토큰을 재발급하는 요청에서도 accessToken과 refreshToken을 주고 있습니다. 따라서 토큰 응답 DTO를 TokenResponse로 통일하고자 재발급용 응답 DTO였던 ReissueTokenResponse를 제거했습니다.

**- 회원 가입 시, 유저의 role을 저장하는 로직 추가**

**- 토큰 재발급 로직 수정**
accessToken 만료 시, refreshToken을 보내면 유효성 검증 후, 기존의 refreshToken 삭제 후, accessToken과 refreshToken을 재발급해서 응답으로 전송

**- HttpResponseUtil 클래스**
LoginFilter에서 응답 작성 로직을 분리하고자 해당 클래스를 구현했습니다.

✔ 969f4c07a11aed3706c805f9740df72aa4de7322 : @Getter 제거

✔ 7e6ef9c16f6bb308c71a719b5fa2fd6b4b4918a1 : 토큰 저장 시 만료시간 초 단위로 설정

**- 토큰 저장 시 만료시간 초 단위로 저장되도록 수정**
refreshToken 저장 시 저장하는 로직인 RefreshTokenService의 saveToken에서 토큰 만료시간을 밀리 단위로 받아온 후, 초 단위로 변환하여 저장하는 로직으로 수정하여 redis 저장소에 초 단위로 저장되도록 수정했습니다.

✔ 9865461849bb85c79b193450db39ceac20c3bafe : 토큰 유효 시간 단위 변경

**- 토큰 유효 시간 단위 변경 (Milliseconds -> Seconds)**
기존엔 토큰의 만료 시간 단위를 밀리초로 설정했었습니다. 더 세밀한 설정을 위해 밀리초로 설정했었는데, JWT는 exp를 초 단위로 저장하므로 실제 JWT 토큰의 만료 시간 설정에 반영되지 않음을 알게되었습니다

**- 시간 처리 방식 변경 (ZonedDateTime -> Instant)**
기존엔 JWT 라이브러리와의 호환성을 위해 Date 객체를 사용했으며 Date 객체로 변환하기 위해 Instant로 변환했었습니다. 하지만 Instant는 타임존 개념이 없으므로 ZonedDateTime에서 Instant 로 변환하면 시간대 정보가 제거됨을 확인할 수 있었고, Instant로 변경하였습니다.

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

**1. 토큰 재발급 시, refreshToken 검증 로직**

현재 로직에는 토큰의 유효성을 검증하는 로직 2가지가 구현되어 있습니다.

(1) JwtUtil에서 isTokenValid : 토큰이 만료되었는지 확인하여 토큰의 유효성 검증
(2) RefreshTokenService에서 validateRefreshToken : refreshToken의 경우 발급 후 redis 저장소에 저장됨. 저장되어 있는 refreshToken을 조회하여 얻은 유저 email과 요청 헤더에서 받은 refreshToken에서  추출한 email을 비교하여 두 토큰의 일치 여부로 refreshToken의 유효성 검증

2가지 검증 로직을 모두 거치는 것이 옳은 선택일지 고민해봤습니다. 검증 로직 (1)을 거치면서 1차적으로 먼저 만료된 토큰이나 형식 자체가 유효하지 않은 토큰을 필터링하여 검증된 토큰들만 검증 로직 (2)를 거치게 하면 데이터베이스에 불필요한 접근을 줄일 수 있을 것이라고 판단하여 현재 토큰 재발급 로직에선 두 가지 유효성 검증을 모두 거치도록 구현해두었습니다. 해당 로직에 대해서 어떻게 생각하시는지 궁금합니다.

**2. RefreshToken 관련 로직 분리**

refreshToken의 경우 redis 저장소에 저장해두면서, refreshToken의 저장, 삭제, 검증 로직을 RefreshTokenService에 구현해두었습니다. jwt 토큰의 생성 및 검증 로직을 담당하는 JwtUtil이 있지만, 관심사의 분리를 고려해서 refreshToken의 저장, 삭제, 검증 로직을 RefreshTokenService에 따로 두었습니다. 하지만 accessToken과 refreshToken의 경우 "생성" 로직이 같으므로 (만료시간 차이) 코드 중복을 최소화하기 위해 refreshToken 생성 로직은 JwtUtil에 구현했습니다.
refreshToken의 데이터베이스 처리와 유효성 검증 로직 : RefreshTokenService
refreshToken의 생성 로직 : JwtUtil

더 좋은 설계가 있을지 고민해보겠습니다. 

**3. RefreshToken 관련 클래스 디렉토리 구조**
RefreshToken, Service, Repository를 account 디렉토리 내부에 두었는데, security 디렉토리 내부로 옮기는 것이 좋을지 고민 중입니다.

**4. 시간 처리 방식**
Date 클래스가 시간대 정보를 포함하지 않는 부분에서 LocalDateTime을 사용하면 시간대를 설정할 수 있을 것 같습니다. 다만 Jwts의 setIssuedAt과 setExpiration은 LocalDateTime을 지원하지 않기 때문에 claim에 "exp"와 "iat"를 직접 설정해주는 방식으로 수정할 예정입니다. 

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-07-07 05:26 UTC, catturtle123 requested changes

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/domain/account/controller/AuthController.java
> +    public BaseResponse<TokenResponse> logIn(@RequestBody @Valid LogInRequest request) {
필요없을 것 같습니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/domain/account/controller/AuthController.java
> +    @Operation(summary="카카오 로그인 API", description="카카오 accessToken을 이용하여 유저 정보 받아 저장하고 앱의 토큰 반환" )
social login도 api는 필요 없을 것 같습니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/domain/account/entity/RefreshToken.java
> +public class RefreshToken {
redis를 쓰는 것이 좋아보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/config/CorsConfig.java
> +    public static CorsConfigurationSource apiConfigurationSource() {
cors 해결 부분이 이미 있기 때문에 필요없어 보입니다. conflict 해결하면서 합쳐주세요

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/annotation/ExtractTokenArgumentResolver.java
> +    public boolean supportsParameter(MethodParameter parameter) {
어노테이션 검증이 필요해 보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
> +            "/swagger",
이 url은 필요없어 보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
> +            "/swagger-ui.html",
이 url도 필요없어 보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
> +        http.cors(cors -> cors
cors 설정은 develop에서 받아온 후 합쳐주세요

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/exception/JwtAccessDeniedHandler.java
> +                ErrorStatus._FORBIDDEN.getCode(),
auth쪽 에러로 새로 바꾸는 것이 좋아보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/exception/JwtAuthenticationEntryPoint.java
> +                ErrorStatus._UNAUTHORIZED.getCode(),
여기는 인증이 안되는 것인 것이기 때문에 관련 에러 설정이 필요해보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
> +        return (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) ? bearerToken.replace("Bearer ", ""): null;
bearer토큰인지 아닌지 검증이 필요해 보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/filter/LoginFilter.java
> +        BaseResponse<Object> errorResponse = BaseResponse.onSuccess(tokenResponse);
여기는 성공 response인데 errorResponse라고 되어있는 것이 이상해 보입니다.

2024-07-07 05:26 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/principal/PrincipalDetails.java
> +        roles.add("ROLE_USER");
DB에서 가져오는 것으로 수정이 필요해보입니다.

2024-07-07 05:29 UTC, catturtle123 requested changes

2024-07-07 05:29 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/config/SwaggerConfig.java
> +        Info info = new Info().title("Moim API").description("Moim API 명세").version("1.0.0");
아직 정식 release가 아니기 때문에 버전이 0점 대가 좋아보입니다.

2024-07-07 05:29 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/config/SwaggerConfig.java
> +        SecurityScheme securityScheme = new SecurityScheme()
여긴 바꾼 이유가 있을까요?

2024-07-07 06:21 UTC, yewonahn commented on src/main/java/com/dev/moim/domain/account/entity/RefreshToken.java
> +public class RefreshToken {
refresh token 관리 부분에서 redis를 사용하면 이점이 많은 것 같네요! 더 찾아보면서 고려해보겠습니다

2024-07-07 06:22 UTC, yewonahn commented on src/main/java/com/dev/moim/domain/account/controller/AuthController.java
> +    public BaseResponse<TokenResponse> logIn(@RequestBody @Valid LogInRequest request) {
filter단에서 스웨거 적용되도록 구현하는 중 입니다! 적용한 후 이 부분 제거하도록 하겠습니다

2024-07-07 06:23 UTC, yewonahn commented on src/main/java/com/dev/moim/domain/account/controller/AuthController.java
> +    @Operation(summary="카카오 로그인 API", description="카카오 accessToken을 이용하여 유저 정보 받아 저장하고 앱의 토큰 반환" )
넵! 마찬가지로 소셜 로그인 구현하면서 이 부분도 filter단에서 스웨거 적용되도록 하겠습니다

2024-07-07 06:23 UTC, yewonahn commented on src/main/java/com/dev/moim/global/config/CorsConfig.java
> +    public static CorsConfigurationSource apiConfigurationSource() {
넵 확인했습니다

2024-07-07 06:24 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
> +            "/swagger",
넵 allowUrls 정리했습니다

2024-07-07 06:51 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/exception/JwtAccessDeniedHandler.java
> +                ErrorStatus._FORBIDDEN.getCode(),
인증된 사용자가 필요한 권한이 없이 접근하는 예외를 나타내는 USER_INSUFFICIENT_PERMISSION 에러 추가하겠습니다

2024-07-07 06:53 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/exception/JwtAuthenticationEntryPoint.java
> +                ErrorStatus._UNAUTHORIZED.getCode(),
인증되지 않은 사용자가 접근한 경우이므로 인증이 필요함을 나타내는 USER_AUTHENTICATION_REQUIRED ErrorStatus 추가하겠습니다

2024-07-07 06:53 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/filter/LoginFilter.java
> +        BaseResponse<Object> errorResponse = BaseResponse.onSuccess(tokenResponse);
오타가 있었습니다..! 수정하겠습니다

2024-07-07 06:54 UTC, yewonahn commented on src/main/java/com/dev/moim/global/config/SwaggerConfig.java
> +        Info info = new Info().title("Moim API").description("Moim API 명세").version("1.0.0");
넵 수정하겠습니다

2024-07-07 08:05 UTC, catturtle123 commented on src/main/java/com/dev/moim/domain/account/controller/AuthController.java
> +    public BaseResponse<TokenResponse> logIn(@RequestBody @Valid LogInRequest request) {
넵 알겠습니다

2024-07-07 08:05 UTC, catturtle123 commented on src/main/java/com/dev/moim/domain/account/controller/AuthController.java
> +    @Operation(summary="카카오 로그인 API", description="카카오 accessToken을 이용하여 유저 정보 받아 저장하고 앱의 토큰 반환" )
넵 알겠습니다

2024-07-08 14:42 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/principal/PrincipalDetails.java
> +        roles.add("ROLE_USER");
인가 부분 구현하면서 수정하겠습니다!

2024-07-09 13:49 UTC, yewonahn reviewed
리뷰 코멘트 확인했습니다

2024-07-09 13:49 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
> +        return (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) ? bearerToken.replace("Bearer ", ""): null;
넵 검증 로직 추가했습니다!

2024-07-09 13:49 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/annotation/ExtractTokenArgumentResolver.java
> +    public boolean supportsParameter(MethodParameter parameter) {
넵 @ExtractToken에 대해서만 작동하도록 수정했습니다.

2024-07-09 13:51 UTC, yewonahn commented on src/main/java/com/dev/moim/global/config/SwaggerConfig.java
> +        SecurityScheme securityScheme = new SecurityScheme()
SwaggerConfig 수정했습니다!

2024-07-09 13:52 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/annotation/ExtractTokenArgumentResolver.java
> +    public boolean supportsParameter(MethodParameter parameter) {
넵 @ExtractToken에 대해서만 작동하도록 수정했습니다

2024-07-09 17:08 UTC, catturtle123 requested changes

2024-07-09 17:08 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/util/JwtUtil.java
> +            return claims.getBody().getExpiration().getTime();
시간 단위 확인해주세요.

2024-07-10 04:33 UTC, yewonahn commented on src/main/java/com/dev/moim/global/security/util/JwtUtil.java
> +            return claims.getBody().getExpiration().getTime();
7e6ef9c16f6bb308c71a719b5fa2fd6b4b4918a1

refreshToken을 저장 하는 RefreshTokenService의 saveToken에서 밀리 단위로 받아온 후, 초 단위로 변환하여 저장하는 로직으로 수정했습니다.

2024-07-10 08:34 UTC, catturtle123 requested changes

2024-07-10 08:34 UTC, catturtle123 commented on src/main/java/com/dev/moim/global/security/util/JwtUtil.java
> +            return claims.getBody().getExpiration().getTime();
현재 환경 변수가 refreshtoken 만료시간이 1209600인데 createToken을 보면 1000을 나누고 second를 추가합니다. 이 부분 확인 바랍니다. (한번 출력해보면서 확인해보면 좋을 것 같습니다.)

2024-07-11 06:05 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-07-11 06:33 UTC, yewonahn commented
고생하셨습니다! 머지하겠습니다 🤓

2024-07-11 06:36 UTC, merged